### PR TITLE
Run tests on Java 17

### PR DESCRIPTION
**Pull request by andreaTP**
This is the core fix for:
https://github.com/exercism/java/issues/2034

### CODE REVIEW

**Review by jmrunkle — APPROVED** [review]

**Review by ErikSchierboom — APPROVED** [review]
Excellent!

**Comment by andreaTP** [comment]
@ErikSchierboom do you plan to eventually merge this PR?

**Comment by iHiD** [comment]
@andreaTP I imagine Erik forgot that you're not a maintainer so can't merge this yourself. You are probably getting close to the level or rep required to become a maintainer now. Take a read of https://exercism.org/docs/community/maintainers and let me know if you'd be interested :)

**Review by jmrunkle — APPROVED** [review]

**Comment by iHiD** [comment]
Thanks @jmrunkle! it'll all just magically happen now - no need for us to do anything! :)

**Comment by ErikSchierboom** [comment]
> I imagine Erik forgot that you're not a maintainer so can't merge this yourself. You are probably getting close to the level or rep required to become a maintainer now. Take a read of https://exercism.org/docs/community/maintainers and let me know if you'd be interested :)

I did! You'd make a great maintainer @andreaTP!

**Pull request merged**
