### PR TITLE
Update Dockerfile

### PR DESCRIPTION
**Pull request by jmrunkle**
Update the Gradle image to support JDK 16.

Addresses https://github.com/exercism/exercism/discussions/5717

### CODE REVIEW

**Comment by ericbalawejder** [comment]
Should we stick to the latest LTR version (Java 11) for production environments? The Java track currently runs on Java 11 and gradle 7.1. Java 17 comes out late this year I believe and we could make the jump shortly after?

**Comment by SleeplessByte** [comment]
LTS please.

**Comment by iHiD** [comment]
@jmrunkle Thanks for fixing this. Are you happy to change it to 11?

**Comment by jmrunkle** [comment]
> @jmrunkle Thanks for fixing this. Are you happy to change it to 11?

Yes, just need to edit it. I find it harder to track down patches than it is when you fully forked a repository.

**Review by iHiD — APPROVED** [review]

**Pull request merged**
