### PR TITLE
Upgrade project-specific outdated libraries

### PR DESCRIPTION
**Pull request by qeeqez**
### Upgrade support libraries

Fixes vulnerabilities, also hides errors in IDE:

Upgrade junit lib 4.13 -> 4.13.2
Upgrade assertj-core 3.15 -> 3.24.2

## Dependencies 

- Main repo exercise's upgrade: exercism/java#2247

### CODE REVIEW

**Comment by qeeqez** [comment]
I have executed Github Actions on my account, and there were no errors. All tests passed successfully.

**Review by ErikSchierboom — COMMENTED** [review]
Great job! Is this backwards compatible? Could you maybe add a new test case that uses the old libraries to verify?

**Review by andrerfcsantos — APPROVED** [review]
Looks good. Thanks for this!

Ran the golden tests on docker and looks good there too.

Needs an approval from @exercism/maintainers-admin still - after that we can merge this together with https://github.com/exercism/java/pull/2247

**Comment by ErikSchierboom** [comment]
> @andrerfcsantos 
I'll approve once we have a new test case added that verifies backwards compatibility!

[> https://github.com/exercism/lfe-test-runner/pull/51#issuecomment-1447869999](https://github.com/exercism/java/pull/2247)
I've left a comment on that PR

**Comment by sanderploegsma** [comment]
The test runner design has changed a bit since this PR was opened, causing some conflicts that need to be resolved. Since this PR has been inactive for a while I'm going to close it for now. @qeeqez if you still want to continue working on this, just drop a message so we'll reopen it.

**Pull request closed without merging**
